//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdo.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjectMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjectMessages() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bdo.Resources.ObjectMessages", typeof(ObjectMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Impossibile eseguire un Clone dell&apos;oggetto in quanto e&apos; attivo l&apos;Object Reference Tracking.
        /// </summary>
        internal static string Base_CloneDisabledTracking {
            get {
                return ResourceManager.GetString("Base_CloneDisabledTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Impossibile eseguire eliminare un oggetto nullo..
        /// </summary>
        internal static string Base_Delete_Null {
            get {
                return ResourceManager.GetString("Base_Delete_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile eseguire il confronto con il sorgente (database) poiche&apos; l&apos;oggetto non risulta caricato (non salvato)..
        /// </summary>
        internal static string Base_DiffSourceNotLoaded {
            get {
                return ResourceManager.GetString("Base_DiffSourceNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - L&apos;indice fornito ({1}) non appartiene alla lista.
        /// </summary>
        internal static string Base_IndexOutOfBounds {
            get {
                return ResourceManager.GetString("Base_IndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La proprieta&apos; {1} non puo&apos; essere utilizzata per l&apos;operazione richiesta..
        /// </summary>
        internal static string Base_InvalidProperty {
            get {
                return ResourceManager.GetString("Base_InvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La chiave {1} non e&apos; definita..
        /// </summary>
        internal static string Base_KeyNotFound {
            get {
                return ResourceManager.GetString("Base_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Il numero di valori forniti in input per la Chiave {1} e&apos; minore del numero di campi da valorizzare..
        /// </summary>
        internal static string Base_KeyValuesLessThanFields {
            get {
                return ResourceManager.GetString("Base_KeyValuesLessThanFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Il numero di valori forniti in input per la Chiave {1} e&apos; maggiore del numero di campi da valorizzare..
        /// </summary>
        internal static string Base_KeyValuesMoreThanFields {
            get {
                return ResourceManager.GetString("Base_KeyValuesMoreThanFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Il numero di valori forniti in input per la Chiave {1} differisce dal numero di campi da valorizzare ({2})..
        /// </summary>
        internal static string Base_KeyValuesNoMatch {
            get {
                return ResourceManager.GetString("Base_KeyValuesNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La definizione della classe prevede che nello Slot sia specificato un DbPrefixKey con chiave &apos;{1}&apos;.
        /// </summary>
        internal static string Base_NoDbPrefixDefined {
            get {
                return ResourceManager.GetString("Base_NoDbPrefixDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; stato specificato alcun valore per la Chiave {1}..
        /// </summary>
        internal static string Base_NoValueForKey {
            get {
                return ResourceManager.GetString("Base_NoValueForKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - L&apos;operazione non e&apos; consentita su un oggetto nullo..
        /// </summary>
        internal static string Base_Null_Input {
            get {
                return ResourceManager.GetString("Base_Null_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operatore non riconosciuto.
        /// </summary>
        internal static string Base_OperatorUnknown {
            get {
                return ResourceManager.GetString("Base_OperatorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operatore non supportato su proprieta&apos;.
        /// </summary>
        internal static string Base_OperatorUnsupportedOnProperty {
            get {
                return ResourceManager.GetString("Base_OperatorUnsupportedOnProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Il metodo &quot;{1}&quot; definito per la proprieta&apos; {2} deve avere un solo parametro dello stesso tipo della proprieta&apos;..
        /// </summary>
        internal static string Base_ProcMethodBadArg {
            get {
                return ResourceManager.GetString("Base_ProcMethodBadArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Il metodo &quot;{1}&quot; definito per la proprieta&apos; {2} non esiste..
        /// </summary>
        internal static string Base_ProcMethodNotFound {
            get {
                return ResourceManager.GetString("Base_ProcMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La proprieta&apos; {1} non consente comparazioni..
        /// </summary>
        internal static string Base_PropertyNotComparable {
            get {
                return ResourceManager.GetString("Base_PropertyNotComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non esiste alcuna proprieta&apos; {1}..
        /// </summary>
        internal static string Base_PropertyNotExists {
            get {
                return ResourceManager.GetString("Base_PropertyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Per eseguire il caricamento sul primo accesso della proprieta&apos; {1} e&apos; necessario che l&apos;oggetto sia in stato caricato..
        /// </summary>
        internal static string Base_PropLoadObjectLoaded {
            get {
                return ResourceManager.GetString("Base_PropLoadObjectLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; stato trovato alcun record per il filtro specificato..
        /// </summary>
        internal static string Base_Record_Filter_NotFound {
            get {
                return ResourceManager.GetString("Base_Record_Filter_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Esistono piu&apos; record con Chiave {1} ({2})..
        /// </summary>
        internal static string Base_RecordKeyMultiple {
            get {
                return ResourceManager.GetString("Base_RecordKeyMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; stato trovato alcun record per Chiave {1} = ({2})..
        /// </summary>
        internal static string Base_RecordKeyNotFound {
            get {
                return ResourceManager.GetString("Base_RecordKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Impossibile salvare un oggetto nullo..
        /// </summary>
        internal static string Base_Save_Null {
            get {
                return ResourceManager.GetString("Base_Save_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lo slot che si sta impostando risulta essere nullo o gia&apos; terminato..
        /// </summary>
        internal static string Base_SwithToNullSession {
            get {
                return ResourceManager.GetString("Base_SwithToNullSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - L&apos;XML fornito non contiene alcun nodo &apos;{1}&apos;.
        /// </summary>
        internal static string Base_XmlNodeNotFound {
            get {
                return ResourceManager.GetString("Base_XmlNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile accedere alle proprieta&apos; di un oggetto eliminato..
        /// </summary>
        internal static string Deleted_CannotGetProperty {
            get {
                return ResourceManager.GetString("Deleted_CannotGetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile impostare proprieta&apos; di un oggetto eliminato..
        /// </summary>
        internal static string Deleted_CannotSetProperty {
            get {
                return ResourceManager.GetString("Deleted_CannotSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Sono stati eliminati piu&apos; record con Chiave {1} ({2})..
        /// </summary>
        internal static string Deleted_MultipleRecords {
            get {
                return ResourceManager.GetString("Deleted_MultipleRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile eseguire operazioni su un oggetto eliminato.
        /// </summary>
        internal static string Deleted_NoAction {
            get {
                return ResourceManager.GetString("Deleted_NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; stato eliminato alcun record con Chiave {1} ({2})..
        /// </summary>
        internal static string Deleted_NoRecord {
            get {
                return ResourceManager.GetString("Deleted_NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile eseguire un confronto con un oggetto nullo..
        /// </summary>
        internal static string Diff_Null {
            get {
                return ResourceManager.GetString("Diff_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile eseguire un confronto con un oggetto di tipo differente ({1})..
        /// </summary>
        internal static string Diff_WrongType {
            get {
                return ResourceManager.GetString("Diff_WrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Sono stati aggiornati piu&apos; record con Chiave {1} ({2})..
        /// </summary>
        internal static string Edit_MultipleRecords {
            get {
                return ResourceManager.GetString("Edit_MultipleRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; stato possibile eseguire l&apos;aggiornamento poiche&apos; non trovato il record per Chiave {1} ({2})..
        /// </summary>
        internal static string Edit_NoRecord {
            get {
                return ResourceManager.GetString("Edit_NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La proprieta&apos; {1} non puo&apos; essere decriptata: {2}.
        /// </summary>
        internal static string Enc_Decrypt_Failure {
            get {
                return ResourceManager.GetString("Enc_Decrypt_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La proprieta&apos; {1} non puo&apos; essere criptata: {2}.
        /// </summary>
        internal static string Enc_Encrypt_Failure {
            get {
                return ResourceManager.GetString("Enc_Encrypt_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile aggiungere oggetti nulli o non salvati.
        /// </summary>
        internal static string List_CannotAddUnsavedObjects {
            get {
                return ResourceManager.GetString("List_CannotAddUnsavedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile eseguire operazioni di aggregazione sulla proprieta&apos; &apos;{1}&apos; non numerica.
        /// </summary>
        internal static string List_CannotAggregateNonNumeric {
            get {
                return ResourceManager.GetString("List_CannotAggregateNonNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Indicizzazione fallita. Sono presenti oggetti &apos;{1}&apos; con medesima Primary Key &apos;{2}&apos;.
        /// </summary>
        internal static string List_CannotBuildIndex {
            get {
                return ResourceManager.GetString("List_CannotBuildIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile attivare la cache dei risultati in quanto non configurata la cache esterna oppure transazione in atto..
        /// </summary>
        internal static string List_CannotSetCacheResult {
            get {
                return ResourceManager.GetString("List_CannotSetCacheResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Il delegato fornito in input non puo&apos; essere NULL..
        /// </summary>
        internal static string List_NullDelegate {
            get {
                return ResourceManager.GetString("List_NullDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La colonna {1} esiste. E&apos; necessario che la query di caricamento lista contenga tale nome..
        /// </summary>
        internal static string List_UnknownColumn {
            get {
                return ResourceManager.GetString("List_UnknownColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile eliminare un oggetto non salvato in precedenza..
        /// </summary>
        internal static string New_CannotDelete {
            get {
                return ResourceManager.GetString("New_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; stato inserito alcun record..
        /// </summary>
        internal static string New_NoRecord {
            get {
                return ResourceManager.GetString("New_NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; stato impostato alcun valore per la proprieta&apos; {1}..
        /// </summary>
        internal static string New_NullNotAllowed {
            get {
                return ResourceManager.GetString("New_NullNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; possibile eseguire l&apos;operazione poiche&apos; esplicitamente disabilitata in fase di progettazione (READONLY)..
        /// </summary>
        internal static string OperationFail_SaveOrDelete {
            get {
                return ResourceManager.GetString("OperationFail_SaveOrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La codifica del valore della proprieta&apos; eccede la massima dimensione del campo specificata ({1}).
        /// </summary>
        internal static string Prop_Enc_Wrong_Length {
            get {
                return ResourceManager.GetString("Prop_Enc_Wrong_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La proprieta&apos; {1} non puo&apos; essere impostata poiche&apos; in sola lettura oppure gestita automaticamente..
        /// </summary>
        internal static string Property_Cannot_Set {
            get {
                return ResourceManager.GetString("Property_Cannot_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Il valore della proprieta&apos; {1} non rientra nell&apos;intervallo imposto {2}-{3}..
        /// </summary>
        internal static string Validate_IntRange {
            get {
                return ResourceManager.GetString("Validate_IntRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La lunghezza della proprieta&apos; {1} e&apos; superiore al vincolo imposto di {2} caratteri..
        /// </summary>
        internal static string Validate_MaxLength {
            get {
                return ResourceManager.GetString("Validate_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La lunghezza della proprieta&apos; {1} non supera il vincolo imposto di almeno {2} caratteri..
        /// </summary>
        internal static string Validate_MinLength {
            get {
                return ResourceManager.GetString("Validate_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La proprieta&apos; {1} e&apos; o fa parte della PrimaryKey: la modifica non e&apos; ammessa..
        /// </summary>
        internal static string Validate_PrimaryKeyModified {
            get {
                return ResourceManager.GetString("Validate_PrimaryKeyModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La proprieta&apos; {1} non rispetta l&apos;espressione di validazione impostata..
        /// </summary>
        internal static string Validate_Regex {
            get {
                return ResourceManager.GetString("Validate_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La validazione base delle proprieta&apos; e&apos; fallita. La lista messaggi contiene i dettagli sugli errori..
        /// </summary>
        internal static string ValidateProperties_Failure {
            get {
                return ResourceManager.GetString("ValidateProperties_Failure", resourceCulture);
            }
        }
    }
}
