//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Data.Objects.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchemaMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchemaMessages() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Business.Data.Objects.Common.Resources.SchemaMessages", typeof(SchemaMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Non e&apos; permessa la definizione multipla dell&apos;attributo {2} sulla stessa proprieta&apos;.
        /// </summary>
        public static string Attr_MultipleDefinition {
            get {
                return ResourceManager.GetString("Attr_MultipleDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; permessa una sola modalita&apos; di trasformazione stringhe tra UpperCase e LowerCase.
        /// </summary>
        public static string Case_OnlyOne {
            get {
                return ResourceManager.GetString("Case_OnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile mappare colonna {0} con ordine {1} poiche&apos; lo stesso ordine appartiene alla colonna {2}..
        /// </summary>
        public static string Column_SameOrder {
            get {
                return ResourceManager.GetString("Column_SameOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - La connessione DB puo&apos; essere definita a livello di attributo Table o attributo DbConnection ma non su entrambi.
        /// </summary>
        public static string DbConnectionAlreadyDefined {
            get {
                return ResourceManager.GetString("DbConnectionAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Il tipo fornito per il database (&apos;{2}&apos;) non esiste..
        /// </summary>
        public static string DBType_NotFound {
            get {
                return ResourceManager.GetString("DBType_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; permessa una sola funzionalita&apos; tra: AutoIncrement, AutoInsertTimestamp, AutoUpdateTimestamp.
        /// </summary>
        public static string ExtraFeature_OnlyOne {
            get {
                return ResourceManager.GetString("ExtraFeature_OnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - La Primary Key non corrisponde a quella dell&apos;oggetto in input..
        /// </summary>
        public static string PrimaryKey_Mismatch {
            get {
                return ResourceManager.GetString("PrimaryKey_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Non e&apos; stata definita alcuna PrimaryKey.
        /// </summary>
        public static string PrimaryKey_NotSet {
            get {
                return ResourceManager.GetString("PrimaryKey_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - La proprieta&apos; di tipo AutoIncrement deve essere di tipo intero di almeno 32 bit.
        /// </summary>
        public static string Prop_AutoInc_32_Bit {
            get {
                return ResourceManager.GetString("Prop_AutoInc_32_Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Una proprietà con attributo AutoIncrement non puo&apos; avere attributo AcceptNull..
        /// </summary>
        public static string Prop_AutoIncAcceptNull {
            get {
                return ResourceManager.GetString("Prop_AutoIncAcceptNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ..
        /// </summary>
        public static string Prop_AutoIncOnlySimple {
            get {
                return ResourceManager.GetString("Prop_AutoIncOnlySimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - E&apos; possibile definire criptata solo una proprieta&apos; di tipo &quot;string&quot;.
        /// </summary>
        public static string Prop_Encryped_Only_String {
            get {
                return ResourceManager.GetString("Prop_Encryped_Only_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Non e&apos; possibile definire contemporaneamente gli attributi InsertTimestamp che UpdateTimestamp..
        /// </summary>
        public static string Prop_ErrorTimestamp {
            get {
                return ResourceManager.GetString("Prop_ErrorTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - L&apos;appartenenza ad una chiave necessita che la proprieta&apos; sia valorizzata nella query standard.
        /// </summary>
        public static string Prop_KeyNeedValueQuery {
            get {
                return ResourceManager.GetString("Prop_KeyNeedValueQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - La cancellazione logica necessita di una proprieta&apos; di tipo intero (di qualunque dimensione byte, int16, int32, int64), booleano o datetime.
        /// </summary>
        public static string Prop_LogicalDeleteWrongType {
            get {
                return ResourceManager.GetString("Prop_LogicalDeleteWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - La proprieta&apos; deve essere una lista.
        /// </summary>
        public static string Prop_Must_Be_List {
            get {
                return ResourceManager.GetString("Prop_Must_Be_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - L&apos;attributo {2} necessita che la proprieta&apos; sia di sola lettura .
        /// </summary>
        public static string Prop_MustBeReadOnlyForAttribute {
            get {
                return ResourceManager.GetString("Prop_MustBeReadOnlyForAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - E&apos; consentito il solo array di tipo byte..
        /// </summary>
        public static string Prop_NoArrayBytes {
            get {
                return ResourceManager.GetString("Prop_NoArrayBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Non e&apos; possibile definire una proprieta&apos; come LowerCase e UpperCase contemporaneamente.
        /// </summary>
        public static string Prop_NoLowerUpperCase {
            get {
                return ResourceManager.GetString("Prop_NoLowerUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Non e&apos; possibile definire una proprieta&apos; con più attributi automatici (AutoIncrement, AutoInsertTimestamp, AutoUpdateTimestamp, ConcurrencyControl).
        /// </summary>
        public static string Prop_NoMultipleAutomatic {
            get {
                return ResourceManager.GetString("Prop_NoMultipleAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Una proprietà mappata su oggetto deve contenere almeno una definizione Column..
        /// </summary>
        public static string Prop_ObjectSpecifyColumns {
            get {
                return ResourceManager.GetString("Prop_ObjectSpecifyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - E&apos; necessario specificare un Order dato per l&apos;attributo Column in quanto presenti piu&apos; attributi Column. Il sistema non e&apos; in grado di garantire l&apos;ordinamento specificato in fase di definizione (gli attributi possono venire letti al contrario!).
        /// </summary>
        public static string Prop_ObjectSpecifyOrder {
            get {
                return ResourceManager.GetString("Prop_ObjectSpecifyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - E&apos; necessario specificare un tipo dato per l&apos;attributo Column..
        /// </summary>
        public static string Prop_ObjectSpecifySubType {
            get {
                return ResourceManager.GetString("Prop_ObjectSpecifySubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - E&apos; possibile definire una PrimaryKey solo su proprieta&apos; non mappate..
        /// </summary>
        public static string Prop_PrimaryKey_SimpleType {
            get {
                return ResourceManager.GetString("Prop_PrimaryKey_SimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Il PropertyMap necessita la specifica di almeno 1 nome proprieta&apos;.
        /// </summary>
        public static string Prop_PropertyMapMissingNames {
            get {
                return ResourceManager.GetString("Prop_PropertyMapMissingNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Il PropertyMap e&apos; necessita che la proprieta&apos; puntata esista e che venga definita prima (nel codice) rispetta alla proprieta&apos; che la mappa. ({2}).
        /// </summary>
        public static string Prop_PropertyMapMustBeFirst {
            get {
                return ResourceManager.GetString("Prop_PropertyMapMustBeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Il PropertyMap e&apos; consentito su una proprieta&apos; di tipo oggetto BDO in sola lettura e non ammette la definizione di attributi Column.
        /// </summary>
        public static string Prop_PropertyMapReadonly {
            get {
                return ResourceManager.GetString("Prop_PropertyMapReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Il PropertyMap e&apos; necessita che la proprieta&apos; puntata deve essere di tipo semplice.
        /// </summary>
        public static string Prop_PropertyMapToSimple {
            get {
                return ResourceManager.GetString("Prop_PropertyMapToSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Il nome della stored procedure associata ad una chiave multipla va specificato solo sulla prima proprieta&apos;.
        /// </summary>
        public static string Prop_StoredProcedure_First {
            get {
                return ResourceManager.GetString("Prop_StoredProcedure_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - L&apos;attributo XmlTag e&apos; valido solo se non fornita una definizione per la colonna (dove e&apos; gia&apos; possibile specificarlo)..
        /// </summary>
        public static string Prop_XmlTagUnused {
            get {
                return ResourceManager.GetString("Prop_XmlTagUnused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - Non e&apos; possibile definire piu&apos; colonne su una proprietà di tipo semplice..
        /// </summary>
        public static string Property_OnlyOneColumn {
            get {
                return ResourceManager.GetString("Property_OnlyOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non e&apos; possibile caricare lo schema per la classe &apos;{0}&apos; poiche&apos; gia&apos; esistente..
        /// </summary>
        public static string Schema_AlreadyExists {
            get {
                return ResourceManager.GetString("Schema_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - E&apos; necessario definire una PrimaryKey..
        /// </summary>
        public static string Schema_NoPrimaryKey {
            get {
                return ResourceManager.GetString("Schema_NoPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - E&apos; necessario definire almeno una proprieta&apos;..
        /// </summary>
        public static string Schema_NoProperties {
            get {
                return ResourceManager.GetString("Schema_NoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lo schema per il tipo &apos;{0}&apos; non risulta essere caricato..
        /// </summary>
        public static string Schema_NotFound {
            get {
                return ResourceManager.GetString("Schema_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}.{1} - L&apos;attributo {2} e&apos; valido solo per proprieta&apos; di tipo &quot;string&quot;..
        /// </summary>
        public static string Type_NotApplicable {
            get {
                return ResourceManager.GetString("Type_NotApplicable", resourceCulture);
            }
        }
    }
}
