//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Data.Objects.Core.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SessionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SessionMessages() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Business.Data.Objects.Core.Common.Resources.SessionMessages", typeof(SessionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La dimensione di cache fornita &apos;{0}&apos; non e&apos; valida. Il valore consentito è tra 1 e 10000..
        /// </summary>
        public static string CacheSizeNotValid {
            get {
                return ResourceManager.GetString("CacheSizeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non e&apos; possibile eliminare il database di default.
        /// </summary>
        public static string Cannot_Delete_Default_DB {
            get {
                return ResourceManager.GetString("Cannot_Delete_Default_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; possibile variare la dimensione della cache della sessione solo se vuota..
        /// </summary>
        public static string CannotChangeCacheSizeNoEmpty {
            get {
                return ResourceManager.GetString("CannotChangeCacheSizeNoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile clonare un oggetto in quanto e&apos; attivo il Live Tracking.
        /// </summary>
        public static string Clone_LiveTrack_Not_Allowed {
            get {
                return ResourceManager.GetString("Clone_LiveTrack_Not_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non e&apos; possibile comparare sessioni nulle..
        /// </summary>
        public static string Compare_Null {
            get {
                return ResourceManager.GetString("Compare_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} - Il custom log va inizializzato chiamando il metodo InitCustomLog(filename).
        /// </summary>
        public static string CustomLog_Not_Initialized {
            get {
                return ResourceManager.GetString("CustomLog_Not_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non esiste alcun database registrato con nome &apos;{0}&apos;.
        /// </summary>
        public static string DB_Not_Exist {
            get {
                return ResourceManager.GetString("DB_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nella inizializzazione dell&apos;ambiente: {0}.
        /// </summary>
        public static string Initialization_Error {
            get {
                return ResourceManager.GetString("Initialization_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La ricerca per filtro necessita di un filtro valorizzato.
        /// </summary>
        public static string LoadObj_Filter_Null {
            get {
                return ResourceManager.GetString("LoadObj_Filter_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La ricerca per chiave &apos;{0}&apos; deve contenere almeno un parametro di ricerca.
        /// </summary>
        public static string LoadObj_Key_NoValue {
            get {
                return ResourceManager.GetString("LoadObj_Key_NoValue", resourceCulture);
            }
        }
    }
}
