//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Data.Objects.Database.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseMessages() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Business.Data.Objects.Database.Resources.DatabaseMessages", typeof(DatabaseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore caricamento classe Factory da &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Assembly_Load_Error {
            get {
                return ResourceManager.GetString("Assembly_Load_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assembly {0} non trovato.
        /// </summary>
        internal static string Assembly_Not_Found {
            get {
                return ResourceManager.GetString("Assembly_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile acquisire il lock richiesto ({0}).
        /// </summary>
        internal static string Cannot_Get_lock {
            get {
                return ResourceManager.GetString("Cannot_Get_lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile rilasciare il lock richiesto ({0}) poiche&apos; ottenuto da altro chiamante.
        /// </summary>
        internal static string Cannot_Release_Lock {
            get {
                return ResourceManager.GetString("Cannot_Release_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La Chiave di ConnectionString fornita &quot;{0}&quot; non esiste nel web.config/app.config.
        /// </summary>
        internal static string ConnKey_NotFound {
            get {
                return ResourceManager.GetString("ConnKey_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il lock {0} non e&apos; acquisito.
        /// </summary>
        internal static string Lock_Not_Acquired {
            get {
                return ResourceManager.GetString("Lock_Not_Acquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il lock richiesto non risulta registrato su questa istanza di database.
        /// </summary>
        internal static string Lock_Reference_Null {
            get {
                return ResourceManager.GetString("Lock_Reference_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il database corrente ({0}) non supporta la funzionalita&apos; richiesta.
        /// </summary>
        internal static string Not_Implemented {
            get {
                return ResourceManager.GetString("Not_Implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il provider {0} non e&apos; riconosciuto. Le possibili opzioni sono: MSSQLDataBase, MSSQL2005DataBase, MYSQLDataBase, SQLITEDataBase.
        /// </summary>
        internal static string Provider_Unknown {
            get {
                return ResourceManager.GetString("Provider_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lo statement SQL non e&apos; valorizzato. Attenzione: dopo ciascuna esecuzione viene cancellato sia lo statement SQL che i parametri..
        /// </summary>
        internal static string Query_Empty {
            get {
                return ResourceManager.GetString("Query_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esito: ERROR.
        /// </summary>
        internal static string TraceLog_Return_ERR {
            get {
                return ResourceManager.GetString("TraceLog_Return_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esito: OK.
        /// </summary>
        internal static string TraceLog_Return_OK {
            get {
                return ResourceManager.GetString("TraceLog_Return_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Transazione non aperta.
        /// </summary>
        internal static string Transaction_Not_Open {
            get {
                return ResourceManager.GetString("Transaction_Not_Open", resourceCulture);
            }
        }
    }
}
